rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

# Don't install local development gems on Travis
bundler_args: --without development

# Only test master
branches:
  only:
    - master

script: bundle exec rspec --color --format progress
