rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3

# Don't install local development gems on Travis, use parallel gem downloads
bundler_args: --without development --jobs 7

# Only test master
branches:
  only:
    - master

script: bundle exec rake
